server:
  port: 8910
  servlet:
    context-path: /zufang

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    check-template-location: true
    request-context-attribute: request
    content-type: text/html
    suffix: .html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/zufang?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      initial-size: 8
      max-active: 20
      min-idle: 8
      max-wait: 60000
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      filter: stat,wall,log4j
      ##### druid 监控 ####
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern:  /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #设置不统计哪些URL
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true #禁止手动重置监控数据
        login-username: admin
        login-password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #不加这句则默认为myisam引擎

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liang.zufang.entity
